spring:
  datasource:
    url: jdbc:mysql://postgresdb:5432/fastfood
    username: fastfooduser
    password: fastfoodpass
  jpa:
    hibernate:
      ddl-auto: update
    driver-class-name: org.postgresql.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true