spring:
  datasource:
    url: jdbc:postgresql://postgresdb/fastfood
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    driver-class-name: org.postgresql.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true