apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  # User DB
  POSTGRES_DB: fastfood
  # Db user
  POSTGRES_USER: fastfooduser
  # Db password
  POSTGRES_PASSWORD: fastfoodpass