apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: svc-mysql
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 32000
  selector:
    app: mysql-pod