apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: "MYSQL_USER"
          value: "fastfooduser"
        - name: "MYSQL_PASSWORD"
          value: "fastfoodpass"
        - name: "MYSQL_DATABASE"
          value: "fastfood"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "fastfoodpass"
      ports:
        - containerPort: 3306