apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-app
  namespace: tech-challenge-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-name: tech-challenge-loadbalancer

spec:
  selector:
    app: tech-challenge-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerClass: nlb
  allocateLoadBalancerNodePorts: false