apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-app
  namespace: tech-challenge-namespace
spec:
  selector:
    app: tech-challenge-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false