name: Build and Deploy to Amazon EKS

on:
  pull_request:
    branches: [develop]
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: public.ecr.aws/n0p9h9c2/dmsec
  EKS_CLUSTER: tech-challenge

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        id: build-maven
        run: mvn -B package --file pom.xml

      - name: Get Project Version from pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion

      - name: Print the version
        run: echo "v${{ steps.getVersion.outputs.version }}"

      - name: Set Git user identity
        run: |
          git config --global user.email "douglasmsi@gmail.com"
          git config --global user.name "Douglas Marra"
          
      - name: Create a release
        id: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Authenticate with AWS ECR Public
        run: |
          aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

  jobName:
    name: Update deploy
    runs-on: ubuntu-latest
    env:
      aws_region: eu-central-1
    steps:
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}
      # --- #
      - name: Build and push CONTAINER_NAME
        id: kubectl
        uses: ianbelcher/eks-kubectl-action@master
        with:
          cluster_name: ${{ env.EKS_CLUSTER }}
          args: set image --record deployment/pod-name pod-name=${{ steps.build.outputs.IMAGE_URL }}

      - name: Use the output
        run: echo "${{ steps.kubectl.outputs.kubectl-out }}"

      - name: Apply to Amazon EKS
        run: kubectl apply -f kubernetes/deployment.yaml
