name: Build and Deploy to Amazon EKS

on:
  pull_request:
    branches: [develop]
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: public.ecr.aws/n0p9h9c2
  EKS_CLUSTER: tech-challenge

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        id: build-maven
        run: mvn -B package --file pom.xml

      - name: Get Project Version from pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion

      - name: Print the version
        run: echo "v${{ steps.getVersion.outputs.version }}"

      - name: Set Git user identity
        run: |
          git config --global user.email "douglasmsi@gmail.com"
          git config --global user.name "Douglas Marra"

      - name: Create an incremental tag
        id: create_tag
        uses: aurestic/incrementarl-create-release@master
        with:
          flag_branch: true
          message: Bump version
          prev_tag: 'v'
          update_odoo_module_version: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Authenticate with AWS ECR Public
        run: |
          aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY }}

      - name: Get Latest Tag
        id: getLatestTag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ steps.getLatestTag.outputs.tag }}
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker tag $IMAGE_TAG public.ecr.aws/n0p9h9c2/$IMAGE_TAG
          docker push ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Create kubeconfig for Amazon EKS
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Deploy to Amazon EKS
        run: kubectl apply -f kubernetes/deployment.yaml
